"""Compile the canonical engine-neutral spec into per-engine instruction files.

Write-once, compile-many (ADR-019): `substrate/methodology.md` is the source;
this module projects it into an engine's instruction file (CLAUDE.md, AGENTS.md,
…). Generated files carry a managed marker so the compiler never silently
clobbers a hand-authored instruction file — it refuses unless the target is
SubstrateOS-managed or ``force`` is given.
"""

from __future__ import annotations

from pathlib import Path

from labctl.engines import EngineAdapter

MANAGED_MARKER = (
    "<!-- generated by SubstrateOS (subos) — do not edit; "
    "edit substrate/methodology.md and recompile -->"
)


def render(spec_text: str, adapter: EngineAdapter) -> str:
    """Render the compiled instruction-file content for one engine."""
    header = f"{MANAGED_MARKER}\n<!-- engine: {adapter.name} -->\n\n"
    return header + spec_text


def is_managed(path: Path) -> bool:
    """True if ``path`` is absent or a SubstrateOS-generated file (safe to write)."""
    if not path.exists():
        return True
    return MANAGED_MARKER in path.read_text(encoding="utf-8", errors="ignore")


def compile_to(
    spec_path: Path,
    adapter: EngineAdapter,
    target_dir: Path,
    *,
    force: bool = False,
) -> Path:
    """Compile ``spec_path`` into ``target_dir``'s instruction file for ``adapter``.

    Refuses to overwrite a non-managed (hand-authored) file unless ``force``.
    Returns the written path.
    """
    spec_text = Path(spec_path).read_text(encoding="utf-8")
    out = Path(target_dir) / adapter.instruction_file
    if not force and not is_managed(out):
        raise FileExistsError(
            f"{out} exists and is not SubstrateOS-managed; pass force=True to overwrite"
        )
    out.parent.mkdir(parents=True, exist_ok=True)
    out.write_text(render(spec_text, adapter), encoding="utf-8")
    return out
