"""Compile the canonical engine-neutral spec into per-engine instruction files.

Write-once, compile-many (ADR-019): `substrate/methodology.md` is the source;
this module projects it into an engine's instruction file (CLAUDE.md, AGENTS.md,
…). Generated files carry a managed marker so the compiler never silently
clobbers a hand-authored instruction file — it refuses unless the target is
SubstrateOS-managed or ``force`` is given.
"""

from __future__ import annotations

from pathlib import Path

from labctl.engines import EngineAdapter

MANAGED_MARKER = (
    "<!-- generated by SubstrateOS (subos) — do not edit; "
    "edit substrate/methodology.md and recompile -->"
)


def render(spec_text: str, adapter: EngineAdapter) -> str:
    """Render the compiled instruction-file content for one engine."""
    header = f"{MANAGED_MARKER}\n<!-- engine: {adapter.name} -->\n\n"
    return header + spec_text


def is_managed(path: Path) -> bool:
    """True if ``path`` is absent or a SubstrateOS-generated file (safe to write)."""
    if not path.exists():
        return True
    return MANAGED_MARKER in path.read_text(encoding="utf-8", errors="ignore")


def compile_to(
    spec_path: Path,
    adapter: EngineAdapter,
    target_dir: Path,
    *,
    force: bool = False,
) -> Path:
    """Compile ``spec_path`` into ``target_dir``'s instruction file for ``adapter``.

    Refuses to overwrite a non-managed (hand-authored) file unless ``force``.
    Returns the written path.
    """
    spec_text = Path(spec_path).read_text(encoding="utf-8")
    out = Path(target_dir) / adapter.instruction_file
    if not force and not is_managed(out):
        raise FileExistsError(
            f"{out} exists and is not SubstrateOS-managed; pass force=True to overwrite"
        )
    out.parent.mkdir(parents=True, exist_ok=True)
    out.write_text(render(spec_text, adapter), encoding="utf-8")
    return out


WARM_COMMAND_TEMPLATE = """{marker}
<!-- engine: {engine} — SubstrateOS warm activation (/substrateos) -->

# /substrateos — activate SubstrateOS in this session

Adopt the SubstrateOS methodology now (see `{instruction_file}` and
`substrate/methodology.md`). Then:

1. Run `labctl status` and `labctl doctor` to hydrate the current build state.
2. Print the capability handshake (MUST vs SHOULD for this engine) and report
   anything you cannot do natively.
3. Drive `labctl` from here on; never bypass the release gate.

Note: warm activation cannot retro-enable launch-time-only features (permission
mode, MCP servers, session-start hooks). For full integration, relaunch with
`subos {engine} --full-auto`.
"""


def compile_warm_command(
    adapter: EngineAdapter,
    target_dir: Path,
    *,
    force: bool = False,
) -> Path | None:
    """Compile the ``/substrateos`` warm-activation command for ``adapter``.

    Returns the written path, or None if the engine has no warm-command slot.
    """
    if not adapter.warm_command_file:
        return None
    out = Path(target_dir) / adapter.warm_command_file
    if not force and not is_managed(out):
        raise FileExistsError(
            f"{out} exists and is not SubstrateOS-managed; pass force=True to overwrite"
        )
    out.parent.mkdir(parents=True, exist_ok=True)
    out.write_text(
        WARM_COMMAND_TEMPLATE.format(
            marker=MANAGED_MARKER,
            engine=adapter.name,
            instruction_file=adapter.instruction_file,
        ),
        encoding="utf-8",
    )
    return out


SKILL_DESCRIPTION = (
    "Use when operating as SubstrateOS — drive labctl, never bypass the release "
    "gate, respect capsule isolation and the review queue."
)

SKILL_TEMPLATE = """---
name: substrateos
description: {description}
---
{marker}

# Operate as SubstrateOS

Full rules: `{instruction_file}` and `substrate/methodology.md`. Core MUST tier,
enforced by the labctl harness on any engine:

- Drive `labctl`; never bypass the seven-stage release gate.
- Respect capsule isolation and memory namespaces; honour the review queue.
- Stay within the token circuit-breaker budget; no secrets in any file.
- Report honestly and self-report capability gaps.
"""


def compile_skill(
    adapter: EngineAdapter,
    target_dir: Path,
    *,
    force: bool = False,
) -> Path | None:
    """Compile the progressive-disclosure ``substrateos`` SKILL.md for ``adapter``.

    Returns the written path, or None if the engine declares no skills dir. The
    instruction file is the lean orientation; this skill carries the on-demand
    detail (progressive disclosure, per the master research).
    """
    if not adapter.skills_dir:
        return None
    out = Path(target_dir) / adapter.skills_dir / "substrateos" / "SKILL.md"
    if not force and not is_managed(out):
        raise FileExistsError(
            f"{out} exists and is not SubstrateOS-managed; pass force=True to overwrite"
        )
    out.parent.mkdir(parents=True, exist_ok=True)
    out.write_text(
        SKILL_TEMPLATE.format(
            description=SKILL_DESCRIPTION,
            marker=MANAGED_MARKER,
            instruction_file=adapter.instruction_file,
        ),
        encoding="utf-8",
    )
    return out
